### ISSUE TITLE
1000000 instead of 10000000000

### ISSUE THREAD

**Issue by Armin12** [brainhack101/exploratory-data-analysis#1]
I tried  jupyter-notebook --NotebookApp.iopub_data_rate_limit=10000000000 and it returned me the following error:
 The 'iopub_data_rate_limit' trait of a NotebookApp instance must be a float, but a value of 10000000000L <type 'long'> was specified.

When I changed it to jupyter-notebook --NotebookApp.iopub_data_rate_limit=1000000, that was the default data rate limit value, it worked!

**Comment by gkiar** [comment]
Thanks! :)
